/** Common public signs. Short meanings for the on-device helper. */
export const SIGN_MEANINGS: Record<string, string> = {
  "emergency exit": "This is a way out if there is danger.",
  "fire exit": "This is a way out if there is a fire.",
  "fire door": "Keep this door shut. It slows a fire.",
  "fire extinguisher": "This can put out a small fire.",
  "assembly point": "Meet here if you must leave the building.",
  "push": "Press the door to open it.",
  "pull": "Draw the door toward you.",
  "push bar": "Press the bar to open the door.",
  "slide": "Move the door to the side.",
  "automatic door": "The door opens by itself. Stand back a little.",
  "keep clear": "Do not block this space.",
  "keep shut": "Close this door and leave it closed.",
  "stop": "Do not go. Wait.",
  "stop here": "Wait at this line.",
  "yield": "Let other people or cars go first.",
  "give way": "Let other people or cars go first.",
  "caution": "Be careful here.",
  "warning": "There is a risk. Slow down and look.",
  "danger": "This can hurt you. Stay back.",
  "high voltage": "Electricity here can hurt you. Stay back.",
  "biohazard": "This material can make you sick. Do not touch.",
  "radioactive": "Stay back unless you work here.",
  "flammable": "This can catch fire. No flames.",
  "no smoking": "Do not smoke here.",
  "no naked flames": "Do not use fire or a lighter here.",
  "closed": "This is not open now.",
  "open": "You may go in.",
  "open 24 hours": "This place stays open all day and night.",
  "occupied": "Someone is using this room.",
  "vacant": "This room is free.",
  "restroom": "This is a toilet.",
  "bathroom": "This is a toilet.",
  "toilets": "This is a toilet.",
  "wc": "This is a toilet.",
  "men": "Toilet or room for men.",
  "women": "Toilet or room for women.",
  "accessible toilet": "A toilet with space for a wheelchair.",
  "out of order": "This is broken. Do not use it.",
  "do not enter": "You must not go in.",
  "do not use": "Leave this alone.",
  "keep out": "You must not go in.",
  "staff only": "Only workers may go in.",
  "authorized personnel only": "Only staff may go in.",
  "authorised personnel only": "Only staff may go in.",
  "private": "This is not for the public.",
  "employees only": "Only workers may go in.",
  "wet floor": "The floor is wet. Walk slowly.",
  "slippery when wet": "The floor may be slick. Walk slowly.",
  "mind the step": "There is a step. Watch your feet.",
  "mind the gap": "There is a space. Watch your step.",
  "watch your step": "Look down. There is a step or gap.",
  "no parking": "Do not leave a car here.",
  "no standing": "Do not stop a car here.",
  "no waiting": "Do not stop a car here.",
  "disabled parking": "Parking for a person with a blue badge.",
  "loading zone": "Only for loading goods. Do not leave a car.",
  "exit": "This is the way out.",
  "way out": "This is the way out.",
  "enter": "This is the way in.",
  "entrance": "This is the way in.",
  "no exit": "You cannot leave this way.",
  "one way": "Go only in the arrow direction.",
  "dead end": "The path stops. You must turn back.",
  "detour": "The usual way is closed. Follow the new path.",
  "stairs": "Use the steps.",
  "stairway": "Use the steps.",
  "elevator": "This box moves between floors.",
  "lift": "This box moves between floors.",
  "escalator": "Moving steps. Hold the rail.",
  "out of service": "This is not working now.",
  "please wait": "Stay here for a short time.",
  "please wait to be seated": "A person will show you a seat.",
  "queue here": "Stand in line here.",
  "line starts here": "Stand in line here.",
  "pay here": "Give money at this desk.",
  "tickets": "Buy or show a ticket here.",
  "information": "Ask for help here.",
  "help point": "Use this to ask for help.",
  "first aid": "Help for a hurt person is here.",
  "aed": "A machine that can help a heart stop.",
  "defibrillator": "A machine that can help a heart stop.",
  "hospital": "A place for medical care.",
  "pharmacy": "A shop for medicine.",
  "prescription": "Medicine a doctor ordered.",
  "no food or drink": "Do not eat or drink here.",
  "no pets": "Do not bring an animal.",
  "guide dogs welcome": "A helper dog may come in.",
  "quiet please": "Keep your voice low.",
  "silence": "Do not talk here.",
  "no photography": "Do not take photos.",
  "cctv in operation": "Cameras are recording here.",
  "this way": "Go in the arrow direction.",
  "turn left": "Go to the left.",
  "turn right": "Go to the right.",
  "straight on": "Keep going forward.",
  "floor wet": "The floor is wet. Walk slowly.",
  "hot surface": "This is hot. Do not touch.",
  "do not touch": "Keep your hands off this.",
  "wash your hands": "Clean your hands with soap and water.",
  "now wash your hands": "Clean your hands with soap and water.",
  "poison": "This can make you very sick. Do not swallow it.",
  "keep away from children": "Do not let a child reach this.",
  "fragile": "This breaks easily. Handle with care.",
  "this side up": "Keep this side facing up.",
  "open here": "Start opening at this spot.",
  "pull to open": "Draw it toward you to open.",
  "push to open": "Press it to open.",
  "in case of fire do not use lift": "If there is a fire, use the stairs, not the lift.",
  "in case of fire use stairs": "If there is a fire, use the steps.",
  "no entry": "You must not go in.",
  "restricted area": "Only some people may go in.",
  "hard hat area": "Wear a helmet here.",
  "ppe required": "Wear safety gear here.",
  "hearing protection": "Cover your ears here.",
  "eye protection": "Wear glasses that protect your eyes.",
  "lost and found": "Ask here if you lost a thing.",
  "customer service": "Ask here for help with a problem.",
  "returns": "Bring goods back here.",
  "self checkout": "You scan and pay by yourself.",
  "cash only": "Pay with notes and coins, not a card.",
  "card only": "Pay with a card, not cash.",
  "out of stock": "This item is gone for now.",
  "sale": "The price is lower for a short time.",
  "free": "You do not pay for this.",
  "reserved": "This seat or spot is saved for someone.",
  "not in service": "This is not working now.",
};
